name: Vercel Deployment

on:
  push:
    branches:
      - master  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Allow unsecure commands
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV


      - uses: actions/checkout@v2
      - uses: ngduc/vercel-deploy-action@master
        with:
          vercel-token: fhnq4sKG7Jv1ghA6tKg0W94z
          vercel-cli: vercel
          github-token: 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
          vercel-org-id: UKcP3gyAufa0VYg2PqFcdq8l
          vercel-project-id: prj_A5Ub2Tq2T7DvhbT5o3spSeFOUDVW 
          working-directory: ./ #Your Working Directory, Optional
          alias-domains: | #Optional
            staging.angular.vercel-action.amond.dev
            pr-{{PR_NUMBER}}.angular.vercel-action.amond.dev
            
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
