name: Vercel Deployment

on:
  pull_request:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Allow unsecure commands
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
    
      - name: Deploy to Staging
        id: deploy-vercel-staging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_STATIC}}
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: Extract Preview URL
        id: extract-preview-url
        run: |
          preview_url=${{ steps.deploy-vercel-staging.outputs.preview-url }}
          echo "::set-output name=preview-url::$preview_url"
          
      - name: Comment Preview URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           pr_number="${{ github.event.pull_request.number }}"
           preview_url="${{ steps.extract-preview-url.outputs.preview-url }}"
    
           # Create a formatted comment with an emoji and a clickable link
           comment=":rocket: **Preview URL**: [View the Preview](${preview_url})"
    
           # Post the comment to the pull request
           gh pr comment "$pr_number" --body "$comment"
